/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Graphicp.java
 *
 * Created on 08/10/2009, 20:42:41
 */

package ui;

/**
 *
 * @author paula
 */
public class Graphicp extends javax.swing.JFrame {

    /** Creates new form Graphicp */
    public Graphicp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fracaonaoconformebuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fracaoehconhecidaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        graphicpjButton = new javax.swing.JButton();
        itensPopulacaoTextField = new javax.swing.JTextField();
        itensNaoConformesjTextField = new javax.swing.JTextField();
        fracaoehconhecidajRadioButton = new javax.swing.JRadioButton();
        fracaoehconhecidajRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Parâmetros para o cálculo da fração não conforme (p)");

        jLabel1.setText("Quantidade de ítens da população:");

        jLabel2.setText("Quantidade de ítens não conformes da população:");

        graphicpjButton.setText("Gerar Gráfico");
        graphicpjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphicpjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fracaoehconhecidaPanelLayout = new javax.swing.GroupLayout(fracaoehconhecidaPanel);
        fracaoehconhecidaPanel.setLayout(fracaoehconhecidaPanelLayout);
        fracaoehconhecidaPanelLayout.setHorizontalGroup(
            fracaoehconhecidaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fracaoehconhecidaPanelLayout.createSequentialGroup()
                .addGroup(fracaoehconhecidaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fracaoehconhecidaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itensNaoConformesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fracaoehconhecidaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(itensPopulacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fracaoehconhecidaPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(graphicpjButton)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        fracaoehconhecidaPanelLayout.setVerticalGroup(
            fracaoehconhecidaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fracaoehconhecidaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fracaoehconhecidaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itensNaoConformesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fracaoehconhecidaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itensPopulacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graphicpjButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        fracaonaoconformebuttonGroup.add(fracaoehconhecidajRadioButton);
        fracaoehconhecidajRadioButton.setText("Fração não conforme é conhecida");
        fracaoehconhecidajRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fracaoehconhecidajRadioButtonActionPerformed(evt);
            }
        });

        fracaonaoconformebuttonGroup.add(fracaoehconhecidajRadioButton1);
        fracaoehconhecidajRadioButton1.setText("Fração não conforme não é conhecida");
        fracaoehconhecidajRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fracaoehconhecidajRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fracaoehconhecidaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fracaoehconhecidajRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fracaoehconhecidajRadioButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fracaoehconhecidajRadioButton)
                    .addComponent(fracaoehconhecidajRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fracaoehconhecidaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graphicpjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphicpjButtonActionPerformed
        // TODO add your handling code here:
    	this.setVisible(false);
    	String qtd_populacao_str = this.itensPopulacaoTextField.getText();
    	Double qtd_populacao = Double.parseDouble(qtd_populacao_str);
    	String qtd_naoconforme_str = this.itensPopulacaoTextField.getText();
    	Double qtd_naoconforme = Double.parseDouble(qtd_naoconforme_str);
    	
    }//GEN-LAST:event_graphicpjButtonActionPerformed

    private void fracaoehconhecidajRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fracaoehconhecidajRadioButtonActionPerformed
        // TODO add your handling code here:
        this.fracaoehconhecidaPanel.setVisible(true);
    }//GEN-LAST:event_fracaoehconhecidajRadioButtonActionPerformed

    private void fracaoehconhecidajRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fracaoehconhecidajRadioButton1ActionPerformed
        // TODO add your handling code here:
        this.fracaoehconhecidaPanel.setVisible(false);
    }//GEN-LAST:event_fracaoehconhecidajRadioButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphicp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fracaoehconhecidaPanel;
    private javax.swing.JRadioButton fracaoehconhecidajRadioButton;
    private javax.swing.JRadioButton fracaoehconhecidajRadioButton1;
    private javax.swing.ButtonGroup fracaonaoconformebuttonGroup;
    private javax.swing.JButton graphicpjButton;
    private javax.swing.JTextField itensNaoConformesjTextField;
    private javax.swing.JTextField itensPopulacaoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
