package ui;

/*
 * ControlChart.java
 *
 * Created on 7 de Abril de 2008, 22:26
 */

/**
 *
 * @author  Administrador
 */
public class SelectBestChart extends javax.swing.JFrame {

	private Main parent;

	/** Creates new form ControlChart */
	public SelectBestChart(Main parent)
	{
		this.parent = parent;        
		initComponents();
		this.tipoDadojLabel.setVisible(false);
		this.fracaojCheckBox.setVisible(false);
		this.contagemjCheckBox.setVisible(false);   
		this.grafRecomendadojLabel.setVisible(false);
		this.xsjLabel.setVisible(false);
		this.xbarRjLabel.setVisible(false);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		varAtribbuttonGroup = new javax.swing.ButtonGroup();
		tamanhoAmostrabuttonGroup = new javax.swing.ButtonGroup();
		tamanhoMudancabuttonGroup = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		peqMudjCheckBox = new javax.swing.JCheckBox();
		grandMudjCheckBox = new javax.swing.JCheckBox();
		jLabel5 = new javax.swing.JLabel();
		nMaior1jCheckBox1 = new javax.swing.JCheckBox();
		nIgual1jCheckBox1 = new javax.swing.JCheckBox();
		varjCheckBox = new javax.swing.JCheckBox();
		atribjCheckBox = new javax.swing.JCheckBox();
		jLabel7 = new javax.swing.JLabel();
		tamanhoAmostrajLabel = new javax.swing.JLabel();
		tipoDadojLabel = new javax.swing.JLabel();
		contagemjCheckBox = new javax.swing.JCheckBox();
		fracaojCheckBox = new javax.swing.JCheckBox();
		xbarRjLabel = new javax.swing.JLabel();
		xsjLabel = new javax.swing.JLabel();
		grafRecomendadojLabel = new javax.swing.JLabel();
		recomendacaojToggleButton1 = new javax.swing.JToggleButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Selecionar Gráfico de Controle");
		setName("control_chart"); // NOI18N
		getContentPane().setLayout(null);

		jPanel1.setLayout(null);
		getContentPane().add(jPanel1);
		jPanel1.setBounds(0, 0, 0, 0);

		tamanhoMudancabuttonGroup.add(peqMudjCheckBox);
		peqMudjCheckBox.setText("Pequena");
		getContentPane().add(peqMudjCheckBox);
		peqMudjCheckBox.setBounds(190, 190, 140, 23);

		tamanhoMudancabuttonGroup.add(grandMudjCheckBox);
		grandMudjCheckBox.setText("Grande");
		getContentPane().add(grandMudjCheckBox);
		grandMudjCheckBox.setBounds(30, 190, 120, 23);

		jLabel5.setText("3) Qual o tamanho da mudança a ser detectada?");
		getContentPane().add(jLabel5);
		jLabel5.setBounds(30, 160, 480, 20);

		tamanhoAmostrabuttonGroup.add(nMaior1jCheckBox1);
		nMaior1jCheckBox1.setText("Maior que 1 (n>1)");
		getContentPane().add(nMaior1jCheckBox1);
		nMaior1jCheckBox1.setBounds(190, 120, 200, 23);

		tamanhoAmostrabuttonGroup.add(nIgual1jCheckBox1);
		nIgual1jCheckBox1.setText("Igual a um (n=1)");
		getContentPane().add(nIgual1jCheckBox1);
		nIgual1jCheckBox1.setBounds(30, 120, 150, 23);

		varAtribbuttonGroup.add(varjCheckBox);
		varjCheckBox.setSelected(true);
		varjCheckBox.setText("Variáveis");
		varjCheckBox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				selectedVariable(evt);
			}
		});
		getContentPane().add(varjCheckBox);
		varjCheckBox.setBounds(30, 60, 130, 23);

		varAtribbuttonGroup.add(atribjCheckBox);
		atribjCheckBox.setText("Atributos");
		atribjCheckBox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				selectedAtributo(evt);
			}
		});
		getContentPane().add(atribjCheckBox);
		atribjCheckBox.setBounds(190, 60, 100, 23);

		jLabel7.setText("1) Os dados coletados são:");
		getContentPane().add(jLabel7);
		jLabel7.setBounds(30, 30, 260, 14);

		tamanhoAmostrajLabel.setText("2) O tamanho da amostra é:");
		getContentPane().add(tamanhoAmostrajLabel);
		tamanhoAmostrajLabel.setBounds(30, 100, 430, 20);

		tipoDadojLabel.setText("2) Qual o tipo de dados?");
		getContentPane().add(tipoDadojLabel);
		tipoDadojLabel.setBounds(30, 100, 410, 20);

		tamanhoAmostrabuttonGroup.add(contagemjCheckBox);
		contagemjCheckBox.setText("Contagem");
		getContentPane().add(contagemjCheckBox);
		contagemjCheckBox.setBounds(190, 120, 200, 23);

		tamanhoAmostrabuttonGroup.add(fracaojCheckBox);
		fracaojCheckBox.setText("Fração");
		getContentPane().add(fracaojCheckBox);
		fracaojCheckBox.setBounds(30, 120, 150, 23);

		xbarRjLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		xbarRjLabel.setText("Xbar, R");
		getContentPane().add(xbarRjLabel);
		xbarRjLabel.setBounds(210, 290, 60, 30);

		xsjLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
		xsjLabel.setText("Xbar, S");
		getContentPane().add(xsjLabel);
		xsjLabel.setBounds(210, 260, 60, 30);

		grafRecomendadojLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		grafRecomendadojLabel.setText("Grafico(s) Recomendado(s):");
		getContentPane().add(grafRecomendadojLabel);
		grafRecomendadojLabel.setBounds(20, 270, 180, 20);

		recomendacaojToggleButton1.setText("Gráfico Indicado");
		recomendacaojToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				recomendacaojToggleButton1recomendarGrafico(evt);
			}
		});
		getContentPane().add(recomendacaojToggleButton1);
		recomendacaojToggleButton1.setBounds(70, 230, 140, 23);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		setBounds((screenSize.width-623)/2, (screenSize.height-362)/2, 623, 362);
	}// </editor-fold>//GEN-END:initComponents

	private void selectedAtributo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectAtributo
		// TODO add your handling code here:
		if (this.atribjCheckBox.isSelected())
		{
			this.tamanhoAmostrajLabel.setVisible(false);
			this.nIgual1jCheckBox1.setVisible(false);
			this.nMaior1jCheckBox1.setVisible(false);
			this.tipoDadojLabel.setVisible(true);
			this.fracaojCheckBox.setVisible(true);
			this.contagemjCheckBox.setVisible(true);

		}
	}//GEN-LAST:event_selectAtributo

	private void selectedVariable(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectedVariable
		// TODO add your handling code here:
		if (this.varjCheckBox.isSelected())
		{
			this.tamanhoAmostrajLabel.setVisible(true);
			this.nIgual1jCheckBox1.setVisible(true);
			this.nMaior1jCheckBox1.setVisible(true);
			this.tipoDadojLabel.setVisible(false);
			this.fracaojCheckBox.setVisible(false);
			this.contagemjCheckBox.setVisible(false);

		}
	}//GEN-LAST:event_selectedVariable

	private void recomendacaojToggleButton1recomendarGrafico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recomendacaojToggleButton1recomendarGrafico
		// TODO add your handling code here:
		if ((this.varjCheckBox.isSelected()) && (this.nMaior1jCheckBox1.isSelected()) && (this.grandMudjCheckBox.isSelected()))
		{
			this.grafRecomendadojLabel.setVisible(true);
			this.xsjLabel.setVisible(true);
			this.xbarRjLabel.setVisible(true);
			

		}
	}//GEN-LAST:event_recomendacaojToggleButton1recomendarGrafico

	/**
	 * @param agrs the command line arguments
	 */



	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox atribjCheckBox;
	private javax.swing.JCheckBox contagemjCheckBox;
	private javax.swing.JCheckBox fracaojCheckBox;
	private javax.swing.JLabel grafRecomendadojLabel;
	private javax.swing.JCheckBox grandMudjCheckBox;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JCheckBox nIgual1jCheckBox1;
	private javax.swing.JCheckBox nMaior1jCheckBox1;
	private javax.swing.JCheckBox peqMudjCheckBox;
	private javax.swing.JToggleButton recomendacaojToggleButton1;
	private javax.swing.ButtonGroup tamanhoAmostrabuttonGroup;
	private javax.swing.JLabel tamanhoAmostrajLabel;
	private javax.swing.ButtonGroup tamanhoMudancabuttonGroup;
	private javax.swing.JLabel tipoDadojLabel;
	private javax.swing.ButtonGroup varAtribbuttonGroup;
	private javax.swing.JCheckBox varjCheckBox;
	private javax.swing.JLabel xbarRjLabel;
	private javax.swing.JLabel xsjLabel;
	// End of variables declaration//GEN-END:variables

}
