/*
 * Frame_Principal.java
 *
 * Created on 5 de Abril de 2008, 01:46
 */


import javax.swing.AbstractButton;
import javax.swing.JFileChooser; 
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.jfree.chart.ChartFrame;

import controlcharts.StandardDeviationChartLimits;

import data.DataSetException;

import statistic.GenericStatistic;
import statistic.MedianStatistic;
import statistic.StandardDeviationStatistic;

import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.EventListener;

/**
 *
 * @author  Administrador
 */
public class Frame_Principal extends javax.swing.JFrame {
	
	/** Creates new form Frame_Principal */
	public Frame_Principal() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        basic_statistic = new javax.swing.JMenuItem();
        control_chart = new javax.swing.JMenuItem();
        normality_test = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Estatístico de Qualidade - CEQ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("frame_principal"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletar(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jSeparator2.setAutoscrolls(true);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 620, 1000, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoscrolls(false);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 990, 550);

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Statistic");

        basic_statistic.setText("Basic Statistic");
        basic_statistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasicStatisticActionPerformed(evt);
            }
        });
        jMenu2.add(basic_statistic);

        control_chart.setText("Control Chart");
        control_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_chartActionPerformed(evt);
            }
        });
        jMenu2.add(control_chart);

        normality_test.setLabel("Normality Test");
        jMenu2.add(normality_test);
        normality_test.getAccessibleContext().setAccessibleName("item");

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleParent(this);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1000)/2, (screenSize.height-700)/2, 1000, 700);
    }// </editor-fold>//GEN-END:initComponents


	private void deletar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletar
//		TODO add your handling code here:

	}//GEN-LAST:event_deletar
        
        private void control_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_chartActionPerformed
// TODO add your handling code here:
        ControlChart interface_control_chart= new ControlChart(this);
        interface_control_chart.show(true);
    }//GEN-LAST:event_control_chartActionPerformed

        
	/*public void tableChanged(TableModelEvent e) {
        int row = e.getFirstRow();
        int column = e.getColumn();
        System.out.print("row: "+row);
        System.out.print("coluna: "+column);
        TableModel model = (TableModel)e.getSource();
        String columnName = model.getColumnName(column);
        System.out.print("coluna: "+columnName);
        Object data = model.getValueAt(row, column);
        
        // Do something with the data...
        
    }*/
	
	public void addLine(DefaultTableModel modelo) {
		modelo.addRow( new String [] {"", ""} );
	}

	/*public void deleteLine(DefaultTableModel modelo) {
		// Obtem a linha selecionada na tabela e chama o método
		// para excluir a linha				
		String valoratual = (String) modelo.getValueAt(line,row);		
		// Verificamos se existe realmente alguma linha selecionada		
		if( linhaSelecionada < 0 ){
			return;
		}else{
			// Remove a linha do modelo
			modelo.removeRow(linhaSelecionada);			
		}
	}*/
	
	private void standard_desviationActionPerformed(java.awt.event.ActionEvent evt) throws DataSetException {//GEN-FIRST:event_standard_desviationActionPerformed
//		TODO add your handling code here:

		GenericStatistic statistic = new StandardDeviationStatistic(true);
		StandardDeviationChartLimits limites = new StandardDeviationChartLimits(); 
		File arquivo = OpenActionPerformed(evt);
		ChartFrame frame = new ChartFrame("Gerando Gráfico", GeraGraficos.lineChart(statistic, arquivo,limites));
		//frame.setLocationByPlatform(true);
		Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
		frame.pack();
		frame.setVisible(true);
	}//GEN-LAST:event_standard_desviationActionPerformed

	private void control_charMediantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_charMediantActionPerformed
//		TODO add your handling code here:
		ControlChart control_chartMedia = new ControlChart(this);		
		control_chartMedia.show(true);
	}//GEN-LAST:event_control_charMediantActionPerformed
	private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//		TODO add your handling code here:
	}//GEN-LAST:event_formWindowOpened

	private void BasicStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasicStatisticActionPerformed
//		TODO add your handling code here:
		BasicStatistic interface_statistic_basics = new BasicStatistic();
		interface_statistic_basics.show(true);
	}//GEN-LAST:event_BasicStatisticActionPerformed

	private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
//		TODO add your handling code here:
		System.exit(EXIT_ON_CLOSE);
	}//GEN-LAST:event_ExitActionPerformed

	private File OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
		return this.abrirArquivo();
	}//GEN-LAST:event_OpenActionPerformed

	public File abrirArquivo()
	{
		JFileChooser chooser = new JFileChooser();
		chooser.showOpenDialog(null);
		File arquivo = chooser.getSelectedFile();

		if(arquivo==null)
		{
			System.out.println("Arquivo null");
		}
		return arquivo;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame_Principal().setVisible(true);   				

			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem basic_statistic;
    private javax.swing.JMenuItem control_chart;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem normality_test;
    // End of variables declaration//GEN-END:variables

}
