/*
 * Frame_Principal.java
 *
 * Created on 5 de Abril de 2008, 01:46
 */
import javax.swing.AbstractButton;
import javax.swing.JFileChooser; 
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import controlcharts.MedianChartLimits;
import org.jfree.chart.ChartFrame;
import controlcharts.GenericChartLimits;
import controlcharts.StandardDeviationChartLimits;
import java.io.File;
import data.DataSetException;

import statistic.GenericStatistic;
import statistic.MedianStatistic;
import statistic.StandardDeviationStatistic;

import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.EventListener;

/**
 *
 * @author  Administrador
 */
public class Frame_Principal extends javax.swing.JFrame {
	
	/** Creates new form Frame_Principal */
	public Frame_Principal() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        basic_statistic = new javax.swing.JMenuItem();
        normality_test = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        median_control_chart = new javax.swing.JMenuItem();
        regression_control_chart = new javax.swing.JMenuItem();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Estat\u00edstico de Qualidade - CEQ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("frame_principal");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletar(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        getAccessibleContext().setAccessibleParent(this);
        jSeparator2.setAutoscrolls(true);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 620, 1000, 30);

        jMenu1.setText("Arquivo");
        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Statistic");
        basic_statistic.setText("Basic Statistic");
        basic_statistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasicStatisticActionPerformed(evt);
            }
        });

        jMenu2.add(basic_statistic);

        normality_test.setLabel("Normality Test");
        jMenu2.add(normality_test);
        normality_test.getAccessibleContext().setAccessibleName("item");

        jMenu3.setLabel("Control Charts");
        median_control_chart.setLabel("Median");
        median_control_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                median_control_chartActionPerformed(evt);
            }
        });

        jMenu3.add(median_control_chart);

        regression_control_chart.setText("Regression");
        regression_control_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regression_control_chartActionPerformed(evt);
            }
        });

        jMenu3.add(regression_control_chart);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1000)/2, (screenSize.height-700)/2, 1000, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void regression_control_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regression_control_chartActionPerformed
// TODO add your handling code here:
                GenericStatistic statistic = new MedianStatistic();
		GenericChartLimits limites = new MedianChartLimits(); 
		File arquivo = abrirArquivo();
		ChartFrame frame;		
		try 
		{
			frame = new ChartFrame("Gerando Gráfico", GeraGraficos.lineChart(statistic, arquivo,limites));
			frame.pack();
			frame.setVisible(true);                        
                        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                          
                        frame.setLocation(200,200);                        
		} catch (DataSetException e) {
			// TODO tratar essa excessão
			e.printStackTrace();
		}
    }//GEN-LAST:event_regression_control_chartActionPerformed

    private void median_control_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_median_control_chartActionPerformed
// TODO add your handling code here:
        ControlChart control_chartMedia = new ControlChart(this);		
	control_chartMedia.show(true);
    }//GEN-LAST:event_median_control_chartActionPerformed


	private void deletar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletar
//		TODO add your handling code here:

	}//GEN-LAST:event_deletar
        
        
	
	private void standard_desviationActionPerformed(java.awt.event.ActionEvent evt) throws DataSetException {//GEN-FIRST:event_standard_desviationActionPerformed
//		TODO add your handling code here:

		GenericStatistic statistic = new StandardDeviationStatistic(true);
		StandardDeviationChartLimits limites = new StandardDeviationChartLimits(); 
		File arquivo = OpenActionPerformed(evt);
		ChartFrame frame = new ChartFrame("Gerando Gráfico", GeraGraficos.lineChart(statistic, arquivo,limites));
		//frame.setLocationByPlatform(true);
		Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();                
		frame.pack();
		frame.setVisible(true);
	}//GEN-LAST:event_standard_desviationActionPerformed

	private void control_charMediantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_charMediantActionPerformed
//		TODO add your handling code here:
		ControlChart control_chartMedia = new ControlChart(this);		
		control_chartMedia.show(true);               
	}//GEN-LAST:event_control_charMediantActionPerformed
	private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//		TODO add your handling code here:
	}//GEN-LAST:event_formWindowOpened

	private void BasicStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasicStatisticActionPerformed
//		TODO add your handling code here:
		BasicStatistic interface_statistic_basics = new BasicStatistic();
		interface_statistic_basics.show(true);
	}//GEN-LAST:event_BasicStatisticActionPerformed

	private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
//		TODO add your handling code here:
		System.exit(EXIT_ON_CLOSE);
	}//GEN-LAST:event_ExitActionPerformed

	private File OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
		return this.abrirArquivo();
	}//GEN-LAST:event_OpenActionPerformed

	public File abrirArquivo()
	{
		JFileChooser chooser = new JFileChooser();
		chooser.showOpenDialog(null);
		File arquivo = chooser.getSelectedFile();

		if(arquivo==null)
		{
			System.out.println("Arquivo null");
		}
		return arquivo;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame_Principal().setVisible(true);   				

			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem basic_statistic;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem median_control_chart;
    private javax.swing.JMenuItem normality_test;
    private javax.swing.JMenuItem regression_control_chart;
    // End of variables declaration//GEN-END:variables

}
